name: Process Redirects and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  process-redirects:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      issues: write
    steps:
      - id: checkout-repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Process redirect files
        run: python scripts/process_redirects.py
        env:
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m 'Set redirect files'
          git push origin gh-pages --force
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm install @octokit/request jsonwebtoken
      - name: Generate JWT
        id: generate_jwt
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > private_key.pem
          echo "APP_ID=${{ secrets.APP_ID }}" >> $GITHUB_ENV
      - name: Read Workflow IDs JSON
        id: read_json
        run: |
          WORKFLOW_IDS=$(cat workflow_ids.json)
          echo "::add-mask::$WORKFLOW_IDS"
          echo "WORKFLOW_IDS=$WORKFLOW_IDS" >> $GITHUB_ENV
      - name: Trigger Workflows
        run: node ./scripts/trigger-workflows.mjs
        env:
          APP_ID: ${{ secrets.APP_ID }}
          WORKFLOW_IDS: ${{ env.WORKFLOW_IDS }}